kind: pipeline
type: docker
name: static

platform:
  os: linux
  arch: arm64

steps:
- name: flake8 code validation
  image: python:3.9-alpine
  commands:
  - pip install flake8
  - flake8
  trigger:
    event:
      include:
      - push
      - pull_request
- name: static type checking
  image: python:3.9
  commands:
  - make prerequisite-ci mypy
  environment:
    PIP_EXTRA_INDEX_URL: https://snapshots.linaro.org/ldcg/python-cache/
  trigger:
    event:
      include:
      - push
      - pull_request
---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: arm64

steps:
- name: run tests
  image: python:3.9
  commands:
  - make prerequisite-ci test
  environment:
    PIP_EXTRA_INDEX_URL: https://snapshots.linaro.org/ldcg/python-cache/
  trigger:
    event:
      include:
      - push
      - pull_request
