kind: pipeline
type: docker
name: static

platform:
  os: linux
  arch: arm64

steps:
- name: flake8 code validation
  image: python:3.9-alpine
  commands:
  - pip install flake8
  - flake8
  trigger:
    event:
      include:
      - push
      - pull_request
# - name: static type checking
#   image: python:3.9
#   commands:
#   - make deps mypy
#   environment:
#     PIP_EXTRA_INDEX_URL: https://snapshots.linaro.org/ldcg/python-cache/
#   trigger:
#     event:
#       include:
#       - push
#       - pull_request
---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: arm64

steps:
- name: run tests
  image: shanduur/dragoneye-ci-base:1.0.0
  commands:
  - make deps test
  environment:
    SKIP: true
    PIP_EXTRA_INDEX_URL: https://snapshots.linaro.org/ldcg/python-cache/
    WANDB_API_KEY:
      from_secret: WANDB_API_KEY
  trigger:
    event:
      include:
      - push
      - pull_request
