kind: pipeline
type: docker
name: static

platform:
  os: linux
  arch: arm64

steps:
- name: flake8 code validation
  image: python:3.9-alpine
  commands:
  - pip install flake8
  - flake8
  trigger:
    event:
      include:
      - push
      - pull_request
- name: static type checking
  image: python:3.9
  commands:
  - apt-get update -y
  - cat debian.depends | xargs apt-get install -y # installing required dependencies
  - pip install pipenv
  - sh -c ./scripts/replace.sh # replace tensorflow
  - pipenv install --system --deploy --ignore-pipfile --dev
  - mypy .
  trigger:
    event:
      include:
      - pull_request
---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: arm64

steps:
- name: run tests
  image: python:3.9
  commands:
  - apt-get update -y
  - cat debian.depends | xargs apt-get install -y # installing required dependencies
  - pip install pipenv
  - sh -c ./scripts/replace.sh # replace tensorflow
  - pipenv install --system --deploy --ignore-pipfile --dev
  - pytest
  trigger:
    event:
      include:
      - pull_request
